# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9387dbe7aad6037e35b0336a436aef853a27f7f659da2290063904eaa79f78054afd638d3eadd6a5412a79055f529baa0dff466a94d0411e126f5d1089ad5d26

test:
  secret_key_base: 4ddc686d35bac7ed6b3dd2b6e72c4dce12cda2d37dfc49bc3e2e8d647d722fd9b5ee8e6667a1e51a757440d751281dd4de143715648bb01f026c80c7ee6bb720

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
